### ISSUE TITLE
README.md中的示例代码“接收数据”部分有误

### ISSUE THREAD

**Issue by JxpoemYui** [Shanyaliux/SerialPortUtils#1]
README.md末尾的“接收数据”部分，`serialPort.getReceivedData`未定义。

应将`serialPort.getReceivedData`改为`serialPort.getReadData`，方法定义在world/shanya/serialportutils/SerialPortCallback.kt中。
```kt
    //接收消息回调
    protected var readDataCallback : ((data:String) -> Unit) ?= null

    //接收消息回调
    fun getReadData(readDataCallback: (result:String) -> Unit) {
        this.readDataCallback = readDataCallback
    }

```

**Comment by Shanyaliux** [comment]
十分感谢，已经纠正错误！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Shanyaliux/SerialPortUtils"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 晚上11:10
收件人:&nbsp;"Shanyaliux/SerialPortUtils"<SerialPortUtils@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Shanyaliux/SerialPortUtils] README.md中的示例代码“接收数据”部分有误 (#1)





 
README.md末尾的“接收数据”部分，serialPort.getReceivedData未定义。
 
应将serialPort.getReceivedData改为serialPort.getReadData，方法定义在world/shanya/serialportutils/SerialPortCallback.kt中。
     //接收消息回调     protected var readDataCallback : ((data:String) -&gt; Unit) ?= null     //接收消息回调     fun getReadData(readDataCallback: (result:String) -&gt; Unit) {         this.readDataCallback = readDataCallback     }

**Comment by Shanyaliux** [comment]
fixed #1
